# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       rpcbind

# >> macros
# << macros

Summary:    portmap replacement which supports RPC over various protocols
Version:    1.2.6
Release:    1
Group:      System
License:    BSD
URL:        https://sourceforge.net/project/rpcbind/
Source0:    %{name}-%{version}.tar.bz2
Source100:  rpcbind.yaml
BuildRequires:  pkgconfig(libtirpc)
BuildRequires:  pkgconfig(libsystemd)
BuildRequires:  systemd

%description
%{summary}.

%if "%{?vendor}" == "chum"
PackagerName: nephros
Categories:
 - Network
 - System
%endif


%package doc
Summary:    Documentation files for %{name}
Group:      Documentation
Requires:   %{name} = %{version}-%{release}

%description doc
%{summary}.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/*
%{_sbindir}/*
%{_mandir}/*/*
%{_unitdir}/*
# >> files
# << files

%files doc
%defattr(-,root,root,-)
%{_mandir}/*/*
# >> files doc
# << files doc
